import type { Metadata } from "next";
import {
  Lora,
  Inter,
  DM_Sans,
  Playfair_Display,
} from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/userContext";
import { StoryProvider } from "@/context/storyContext";
import NavBar from "@/components/layout/essentials/navbar";
import { LoaderProvider } from "@/context/loaderContext";
import { NavigationProvider } from "@/context/navigationContext";

const lora = Lora({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const dmsans = DM_Sans({
  variable: "--font-alt",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const playfair = Playfair_Display({
  variable: "--font-tall",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${lora.variable} ${inter.variable} ${dmsans.variable} ${playfair.variable} scroll-smooth`}
    >
      <body className="min-h-full flex flex-col">
        <UserProvider>
          <StoryProvider>
            <LoaderProvider>
              <NavigationProvider>
                <NavBar />
                <main className="px-4 md:px-8 lg:px-16">{children}</main>
              </NavigationProvider>
            </LoaderProvider>
          </StoryProvider>
        </UserProvider>
      </body>
    </html>
  );
}
